version: 1

formatters:
  default:
    class: logging.Formatter
    format: "[%(asctime)s] %(name)s.%(funcName)s %(levelname)s: %(message)s"
    datefmt: "%Y-%m-%d %H-%M-%S"

handlers:
  file_handler:
    class: logging.FileHandler
    filename: run.log

  console_handler:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    level: DEBUG
    formatter: default

root:
  level: DEBUG
  handlers: [console_handler]
